version: '3'

services:

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=percom_garage
    volumes:
      - pgdata_jenkins:/var/lib/postgresql/data/

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: percom_garage
    restart: always
    volumes:
      - web_app:/app
      - jenkins_data:/var/jenkins_home
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
    links:
      - db

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
    web_app:
    jenkins_data:
    pgdata_jenkins:


