# Generated by Django 3.2 on 2021-07-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0002_auto_20210726_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='vehicule',
        ),
    ]
