# Generated by Django 3.2 on 2021-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0003_remove_client_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('Carrosier', 'Carrosier/Carrosière'), ('Electricien Automobile', 'Electricien_Automobile'), ('Mecanicien Automobile', 'Mecanicien_Automobile'), ('Mecanicien motocycle', 'Mecanicien_motocycle'), ('Peintre en carroserie', 'Peintre_en_carroserie'), ('Technicien en Mecanique', 'Technicien_en_Mecanique')], default='Carrosier', max_length=254),
        ),
    ]
