# Generated by Django 3.2 on 2021-08-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0004_alter_employe_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vehicule',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PercomGarage.vehicules'),
        ),
    ]
