# Generated by Django 3.2 on 2021-08-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0005_client_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='num_chasis',
            field=models.IntegerField(unique=True),
        ),
    ]
