# Generated by Django 3.2 on 2021-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0006_alter_vehicules_num_chasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
