# Generated by Django 3.2 on 2021-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0007_auto_20210805_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cni',
            field=models.IntegerField(max_length=14, unique=True),
        ),
    ]
