# Generated by Django 3.2 on 2021-08-05 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0008_alter_client_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicules',
            name='num_portieres',
            field=models.CharField(default=1, max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,17}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='cni',
            field=models.CharField(default=1, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(default=1, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='nb_portieres',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='num_chasis',
            field=models.CharField(default=1, max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,17}$')]),
        ),
    ]
