# Generated by Django 3.2 on 2021-08-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0009_auto_20210805_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='vehicules',
            name='client',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PercomGarage.client'),
        ),
    ]
