# Generated by Django 3.2 on 2021-08-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0010_auto_20210805_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='nb_portieres',
            field=models.IntegerField(default=1),
        ),
    ]
