# Generated by Django 3.2.13 on 2022-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PercomGarage', '0011_alter_vehicules_nb_portieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=254)),
                ('modele', models.CharField(max_length=254)),
                ('version', models.CharField(max_length=254)),
                ('genre', models.CharField(max_length=254)),
                ('carrosserie', models.CharField(max_length=254)),
                ('energie', models.CharField(max_length=254)),
                ('couleur', models.CharField(max_length=254)),
                ('ingredient', models.CharField(max_length=254)),
            ],
        ),
    ]
